# Use a specific version of Python image to ensure consistency across builds
FROM mcr.microsoft.com/devcontainers/javascript-node:18

RUN sudo apt-get update && sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*
